name: Kustomize Action Testing

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: testing kustomize action
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Kustomize build
      uses: dan-slinky-ckpd/kustomize-github-action@kustomize_download_path
      with:
        kustomize_version: 2.0.3
        kustomize_build_dir: .
        kustomize_comment: false
        kustomize_output_file: manifests.yaml
        enable_alpha_plugins: false
    - name: show manifests
      run: |
        cat manifests.yaml
